# Generated by Django 3.0.5 on 2020-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(),
        ),
    ]
