# Generated by Django 3.0.5 on 2020-04-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20200415_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='featured',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Everywhere'), (2, 'Front Page')], default=0),
        ),
    ]
