# Generated by Django 3.0.5 on 2020-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_novel_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
