# Generated by Django 3.0.5 on 2020-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_auto_20200417_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(),
        ),
    ]
