# Generated by Django 3.0.5 on 2020-04-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_chapter_chapter_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'managed': False},
        ),
    ]
