# Generated by Django 3.0.5 on 2020-04-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_auto_20200419_0834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chapter',
            table='novels_chapter',
        ),
    ]
