# Generated by Django 3.0.5 on 2020-05-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_auto_20200511_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='created_at',
        ),
    ]
